apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nl5i9sw26-go
  janus-idp.io/tekton: nl5i9sw26-go
  backstage.io/kubernetes-id: nl5i9sw26-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nl5i9sw26-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
