apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nl5i9sw26-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nl5i9sw26-go 
  name: nl5i9sw26-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nl5i9sw26-go 
